const data =[
{
    name: "MC Donalds",
    item: "Samosa",
    address: "Karolbag, Delhi",
    varients: ["small", "medium", "large"],
    rating: 3.5,
    prices: [
        {
            small: 200,
            medium: 350,
            large: 400,
        },
    ],
    price: 30,
    category: "nonveg",
    // image: "https://www.dominos.co.in/files/items/Pepper_Barbeque.jpg",
    image: "https://www.2foodtrippers.com/wp-content/uploads/2022/11/Big-Mac-Meal-at-McDonalds-1024x726.jpg.webp",
    description: "MC Donalds I Cheese",
},
{
    name: "MC Donalds",
    item: "Samosa",
    address: "Karolbag, Delhi",
    varients: ["small", "medium", "large"],
    rating: 4.5,
    prices: [
        {
            small: 200,
            medium: 350,
            large: 400,
        },
    ],
    price: 30,
    category: "nonveg",
    image: "https://www.2foodtrippers.com/wp-content/uploads/2022/11/Big-Mac-Meal-at-McDonalds-1024x726.jpg.webp",
    description: "MC Donalds I Cheese",
},
{
    name: "MC Donalds",
    item: "Samosa",
    address: "Karolbag, Delhi",
    varients: ["small", "medium", "large"],
    rating: 2.5,
    prices: [
        {
            small: 200,
            medium: 350,
            large: 400,
        },
    ],
    price: 30,
    category: "nonveg",
    image: "https://www.2foodtrippers.com/wp-content/uploads/2022/11/Big-Mac-Meal-at-McDonalds-1024x726.jpg.webp",
    description: "MC Donalds I Cheese",
},
{
    name: "MC Donalds",
    item: "Samosa",
    address: "Karolbag, Delhi",
    varients: ["small", "medium", "large"],
    rating: 4,
    prices: [
        {
            small: 200,
            medium: 350,
            large: 400,
        },
    ],
    price: 30,
    category: "nonveg",
    image: "https://www.2foodtrippers.com/wp-content/uploads/2022/11/Big-Mac-Meal-at-McDonalds-1024x726.jpg.webp",
    description: "MC Donalds I Cheese",
},
{
    name: "MC Donalds",
    item: "Samosa",
    address: "Karolbag, Delhi",
    varients: ["small", "medium", "large"],
    rating: 4,
    prices: [
        {
            small: 200,
            medium: 350,
            large: 400,
        },
    ],
    price: 30,
    category: "nonveg",
    image: "https://www.2foodtrippers.com/wp-content/uploads/2022/11/Big-Mac-Meal-at-McDonalds-1024x726.jpg.webp",
    description: "MC Donalds I Cheese",
},
{
    name: "MC Donalds",
    item: "Samosa",
    address: "Karolbag, Delhi",
    varients: ["small", "medium", "large"],
    rating: 4,
    prices: [
        {
            small: 200,
            medium: 350,
            large: 400,
        },
    ],
    price: 30,
    category: "nonveg",
    image: "https://www.2foodtrippers.com/wp-content/uploads/2022/11/Big-Mac-Meal-at-McDonalds-1024x726.jpg.webp",
    description: "MC Donalds I Cheese",
},
{
    name: "MC Donalds",
    item: "Samosa",
    address: "Karolbag, Delhi",
    varients: ["small", "medium", "large"],
    rating: 4,
    prices: [
        {
            small: 200,
            medium: 350,
            large: 400,
        },
    ],
    price: 30,
    category: "nonveg",
    image: "https://www.2foodtrippers.com/wp-content/uploads/2022/11/Big-Mac-Meal-at-McDonalds-1024x726.jpg.webp",
    description: "MC Donalds I Cheese",
},
{
    name: "MC Donalds",
    item: "Samosa",
    address: "Karolbag, Delhi",
    varients: ["small", "medium", "large"],
    rating: 4,
    prices: [
        {
            small: 200,
            medium: 350,
            large: 400,
        },
    ],
    price: 30,
    category: "nonveg",
    image: "https://www.2foodtrippers.com/wp-content/uploads/2022/11/Big-Mac-Meal-at-McDonalds-1024x726.jpg.webp",
    description: "MC Donalds I Cheese",
},
{
    name: "MC Donalds",
    item: "Samosa",
    address: "Karolbag, Delhi",
    varients: ["small", "medium", "large"],
    rating: 4,
    prices: [
        {
            small: 200,
            medium: 350,
            large: 400,
        },
    ],
    price: 30,
    category: "nonveg",
    image: "https://www.2foodtrippers.com/wp-content/uploads/2022/11/Big-Mac-Meal-at-McDonalds-1024x726.jpg.webp",
    description: "MC Donalds I Cheese",
},
];

export default data